test-01-failed step

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,6 +1,6 @@
 name: 01-Building Blocks
 
-on: workflow_dispatch
+on: push
 
 jobs:
   echo-hello:
@@ -11,9 +11,9 @@ jobs:
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
-      - name: Succeed Step
+      - name: Failed Step
         run: |
-          echo "I will succeed"
-          exit 0
+          echo "I will failed"
+          exit 1
       - name: Say Goodbye
         run: echo "Goodbye"
